### ISSUE TITLE
Format Code

### ISSUE THREAD

**Issue by tk-png** [NishkarshRaj/Hostel-Pass-Management-Application#8]
Code style should be enforced, primarily to avoid unneccesary merge conflicts but also to make the current code look better. Google Java Style is very common and would improve this project. https://github.com/google/google-java-format

**Comment by NishkarshRaj** [comment]
@tk-png I will surely work on this ASAP as my code is too large to be understood well.
I will also document the Classes and their modules for easier understanding.
